Repository wecode-bootcamp-korea/fullstack2-1st-MRDR-frontend, pull requests merged in 2021-10, with the labels that each got.

#21 Add: 상품 상세 페이지 전체 레이아웃 구현 (이성재, 함준범)
  package-lock.json
  src/pages/Products/AdditionalInfoContainer.js
  src/pages/Products/AdditionalInfoContainer.scss
  src/pages/Products/ImagesContainer.js
  src/pages/Products/ImagesContainer.scss
  src/pages/Products/InfoContainer.js
  src/pages/Products/InfoContainer.scss
  src/pages/Products/Products.js
  src/pages/Products/Products.scss
Labels: Status: 피어 리뷰 요청

#31 Add: 상품 리스트 기본 기능구현 (이민재)
  public/data/ProductListData.json
  public/index.html
  src/Routes.js
  src/pages/Productlists/PagiNation/PagiNation.js
  src/pages/Productlists/PagiNation/PagiNation.scss
  src/pages/Productlists/ProductCard/ProductCard.js
  src/pages/Productlists/ProductCard/ProductCard.scss
  src/pages/Productlists/ProductList.js
  src/pages/Productlists/ProductList.scss
  src/pages/Productlists/ProductSubCategory/ProductSubCategories.js
  src/pages/Productlists/ProductSubCategory/ProductSubCategories.scss
  src/styles/reset.scss
Labels: Status: Self Refactoring 완료

#24 Add: 상품 상세 페이지 - 이미지 컨테이너 (함준범)
  package-lock.json
  package.json
  public/data/productImagesData.json
  src/Routes.js
  src/pages/ProductList/PagiNation/PagiNation.js
  src/pages/ProductList/PagiNation/PagiNation.scss
  src/pages/ProductList/ProductCard/ProductCard.js
  src/pages/ProductList/ProductCard/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/ProductSubCategory/ProductSubCategories.js
  src/pages/ProductList/ProductSubCategory/ProductSubCategories.scss
  src/pages/Products/ImagesContainer.js
  src/pages/Products/ImagesContainer.scss
  src/pages/Products/SubImage.js
  src/pages/Products/SubImage.scss
Labels: Status: 피어 리뷰 요청

#33 Add: 상품 상세 페이지 - 추가 정보 컨테이너 (함준범)
  public/data/productColorsData.json
  src/pages/Products/AdditionalInfoContainer.js
  src/pages/Products/AdditionalInfoContainer.scss
  src/pages/Products/AdditionalInfoContainer/AdditionalInfoContainer.js
  src/pages/Products/AdditionalInfoContainer/AdditionalInfoContainer.scss
  src/pages/Products/AdditionalInfoContainer/AdditionalInfoTap/AdditionalInfoTap.js
  src/pages/Products/AdditionalInfoContainer/AdditionalInfoTap/AdditionalInfoTap.scss
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorImageCarousel/ColorImageBox.js
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorImageCarousel/ColorImageBox.scss
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorImageCarousel/ColorImageCarousel.js
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorImageCarousel/ColorImageCarousel.scss
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorPicker/ColorBox.js
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorPicker/ColorBox.scss
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorPicker/ColorPicker.js
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/ColorPicker/ColorPicker.scss
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/DetailInfoContainer.js
  src/pages/Products/AdditionalInfoContainer/DetailInfoContainer/DetailInfoContainer.scss
  src/pages/Products/AdditionalInfoContainer/PurchasingGuide/PurchasingGuide.js
  src/pages/Products/AdditionalInfoContainer/PurchasingGuide/PurchasingGuide.scss
  src/pages/Products/ImagesContainer.js
  src/pages/Products/ImagesContainer.scss
  src/pages/Products/InfoContainer.js
  src/pages/Products/InfoContainer.scss
  src/pages/Products/Products.js
  src/styles/common.scss
  src/util/constants.js
Labels: Status: 피어 리뷰 요청

#37 Fix: 상품 상세 페이지 - 이미지 컨테이너 리팩토링 & 로직 오류 수정
  src/pages/Products/ImagesContainer/ImagesContainer.js
  src/pages/Products/ImagesContainer/ImagesContainer.scss
  src/pages/Products/ImagesContainer/SubImage.js
  src/pages/Products/ImagesContainer/SubImage.scss
  src/pages/Products/Products.js
  src/pages/Products/Products.scss
  src/util/constants.js
Labels: Status: 피어 리뷰 요청

#27 Add: navbar(김원영)
  public/data/menuList.json
  public/image/facebook.png
  public/image/insta.png
  public/image/logo.png
  public/image/youtube.png
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: Conflict 해결 요청, Status: 수정 요청

#44 Add: Color Option carousel 구현
  public/data/productOptionsData.json
  src/pages/ProductList/ProductCard/ProductCard.scss
  src/pages/Products/BasicInfoAndOptionsContainer/BasicInfoAndOptionsContainer.js
  src/pages/Products/BasicInfoAndOptionsContainer/BasicInfoContainer/BasicInfoContainer.js
  src/pages/Products/BasicInfoAndOptionsContainer/BasicInfoContainer/BasicInfoContainer.scss
  src/pages/Products/BasicInfoAndOptionsContainer/Line.js
  src/pages/Products/BasicInfoAndOptionsContainer/Line.scss
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/ColorOptionList/ColorOption/ColorOption.js
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/ColorOptionList/ColorOptionList.js
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/ColorOptionList/ColorOptionList.scss
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/ColorOptionSlider/ColorOption/ColorOption.js
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/ColorOptionSlider/ColorOption/ColorOption.scss
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/ColorOptionSlider/ColorOptionSlider.js
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/ColorOptionSlider/ColorOptionSlider.scss
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/OptionsContainer.js
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/OptionsContainer.scss
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/SizeButtonList/SizeButton/SizeButton.js
  src/pages/Products/BasicInfoAndOptionsContainer/OptionsContainer/SizeButtonList/SizeButtonList.js
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedItemList/SelectedItem/SelectedItem.js
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedItemList/SelectedItem/SelectedItem.scss
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedItemList/SelectedItemList.js
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedItemList/SelectedItemList.scss
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedOption/SelectedOption.js
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedOption/SelectedOption.scss
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedOptionList/SelectedOptionList.js
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectedOptionList/SelectedOptionList.scss
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectionsContainer.js
  src/pages/Products/BasicInfoAndOptionsContainer/SelectionsContainer/SelectionsContainer.scss
Labels: Status: 피어 리뷰 요청

#47 Fix:로그인기능 백앤드와 연결 완료(박정훈)
  src/pages/Login/Login.js
  src/util/constants.js
  src/util/fetch.js
Labels: Status: Accepted

#49 fix:회원가입과 로그인 기능 백엔드와 연결 완료(박정훈)
  src/pages/Cart/utils.js
  src/pages/Login/Login.js
  src/pages/SignUp/AgreePolicyTable/AgreePolicyTable.js
  src/pages/SignUp/BasicUserInfoTable/BasicUserInfoTable.js
  src/pages/SignUp/IdTableRow/IdTableRow.js
  src/pages/SignUp/PhoneTableRow/PhoneTableRow.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/components/TableRows/TableRows.js
  src/util/constants.js
  src/util/fetch.js
Labels: Status: Accepted
